### ISSUE TITLE
FMF 0.9.7 doesn't compile with Qt5.6.0 (beta) on Ubuntu 14.04

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#97]
serializer.cpp 
    error 'QHash' does not name a type.

Qt 5.6 was installed with Qt's snapshot binary.
Probably linked to a change in the way <QHash> is NOT included anymore by other headers in Qt > 5.3 installed from Qt.
Let's try including it in serializer.h

**Comment by jeromecc** [comment]
same with QVariant
in serializer.h adding
    #include <QVariant>
fixed compilation error
