### ISSUE TITLE
FMF EMR v0.9.4 fsp/fsp.cc compilation error with Qt 5 on Arch Linux

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#49]
Version affected: 0.9.4
On Arch Linux, using Qt 5
Compilation error:

g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_REENTRANT -Wall -W -fPIC -DTOOLS_LIBRARY -DFREEMEDFORMS -DWITH_AGENDA -DWITH_ALERTS -DWITH_FEEDBACK -DWITH_PAD -DWITH_PMH -DWITH_WEBCAM -DDRUGS_DATABASE_VERSION=0x000804 -DWITH_EPISODE_REMOVAL -DWITH_CHEQUE_PRINTING -DWITH_FRENCH_FSP -DWITH_FRENCH_HPRIM_INTEGRATOR -DFULLAPPLICATION_BUILD -DBINARY_NAME="\"Tools\"" -DBUILD_PATH_POSTFIXE="\"FreeMedForms\"" -DPACKAGE_VERSION="\"0.9.4\"" -DSOURCES_ROOT_PATH="\"/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4\"" -DLINUX_INTEGRATED -DLINUX_QT_PATH="\"/usr/lib\"" -DLINUX_QT_PLUGINS_PATH="\"/usr/lib/qt/plugins\"" -DLIBRARY_BASENAME="\"lib\"" -DLINUX_PLUGIN_PATH="\"/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/pkg/freemedforms-project/usr//lib/Tools\"" -DGIT_REVISION_HASH="\"85e3fc70e9a2238c0e844d5368d19a0e5676bd45\"" -DQT_NO_CAST_TO_ASCII -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DRELEASE -DQT_DISABLE_DEPRECATED_BEFORE=0x040900 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I. -I/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/plugins -I/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/libs -I/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/contrib -I/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/contrib/quazip -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtScript -isystem /usr/include/qt/QtCore -I/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/build/Qt5_linux-gpp/FreeMedForms/Tools/.moc -I/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/build/Qt5_linux-gpp/FreeMedForms/.ui -I/usr/lib/qt/mkspecs/linux-g++ -o /tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/build/Qt5_linux-gpp/FreeMedForms/Tools/.obj/unix/fsp.o fsp/fsp.cpp
In file included from fsp/fsp.cpp:27:0:
fsp/fsp.h:132:35: erreur: ‘QVariant’ does not name a type
     bool setData(int index, const QVariant &value);
                                   ^
fsp/fsp.h:133:5: erreur: ‘QVariant’ does not name a type
     QVariant data(int index) const;
     ^
fsp/fsp.h:135:51: erreur: ‘QVariant’ does not name a type
     void addAmountData(int line, int index, const QVariant &value);
                                                   ^
fsp/fsp.h:136:5: erreur: ‘QVariant’ does not name a type
     QVariant amountLineData(int line, int index) const;
     ^
fsp/fsp.cpp:359:6: erreur: prototype for ‘bool Tools::Internal::Fsp::setData(int, const QVariant&)’ does not match any in class ‘Tools::Internal::Fsp’
 bool Fsp::setData(int index, const QVariant &value)
      ^
In file included from fsp/fsp.cpp:27:0:
fsp/fsp.h:132:10: erreur: candidates are: bool Tools::Internal::Fsp::setData(int, const int&)
     bool setData(int index, const QVariant &value);
          ^
fsp/fsp.h:124:10: erreur:                 void Tools::Internal::Fsp::setData()
     void setData();
          ^
fsp/fsp.cpp:365:31: erreur: no ‘QVariant Tools::Internal::Fsp::data(int) const’ member function declared in class ‘Tools::Internal::Fsp’
 QVariant Fsp::data(int index) const
                               ^
fsp/fsp.cpp:370:6: erreur: prototype for ‘void Tools::Internal::Fsp::addAmountData(int, int, const QVariant&)’ does not match any in class ‘Tools::Internal::Fsp’
 void Fsp::addAmountData(int line, int index, const QVariant &value)
      ^
In file included from fsp/fsp.cpp:27:0:
fsp/fsp.h:135:10: erreur: candidate is: void Tools::Internal::Fsp::addAmountData(int, int, const int&)
     void addAmountData(int line, int index, const QVariant &value);
          ^
fsp/fsp.cpp:376:51: erreur: no ‘QVariant Tools::Internal::Fsp::amountLineData(int, int) const’ member function declared in class ‘Tools::Internal::Fsp’
 QVariant Fsp::amountLineData(int line, int index) const
                                                   ^
Makefile:1019 : la recette pour la cible « /tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/build/Qt5_linux-gpp/FreeMedForms/Tools/.obj/unix/fsp.o » a échouée
make[3]: *** [/tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/build/Qt5_linux-gpp/FreeMedForms/Tools/.obj/unix/fsp.o] Erreur 1
make[3] : on quitte le répertoire « /tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/plugins/toolsplugin »
Makefile:634 : la recette pour la cible « sub-------plugins-toolsplugin-make_first » a échouée
make[2]: *** [sub-------plugins-toolsplugin-make_first] Erreur 2
make[2] : on quitte le répertoire « /tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/freemedforms/plugins »
Makefile:131 : la recette pour la cible « sub-plugins-make_first-ordered » a échouée
make[1]: *** [sub-plugins-make_first-ordered] Erreur 2
make[1] : on quitte le répertoire « /tmp/yaourt-tmp-ed0c/aur-freemedforms-project/src/freemedforms-project-0.9.4/freemedforms »
Makefile:42 : la recette pour la cible « sub-freemedforms-make_first » a échouée
make: *** [sub-freemedforms-make_first] Erreur 2

**Comment by jeromecc** [comment]
As suggested by @benjarobin missing
#include <QVariant>
 in fsp.h

**Comment by ed0c** [comment]
The compilation error is gone. 
Thanks again for your responsiveness !
But do you think there is a way to make it work with the stable branch ?

**Comment by jeromecc** [comment]
For now, the only stable branch is master. :-) After 0.9.6 release we might start working on a 0.9.4 branch to provide patches to distributions whose policy is not to accept upgrades, but to accept patches for release critical bugs (freezed Debian Jessie). We would only work for a 0.9.4 branch if it's useful for the Debian package.
There are no new features between 0.9.4 and 0.9.6, so the distinction is only formal. In the end a patched 0.9.4 could be similar to 0.9.6, but for Arch Linux there is no reason to stick with 0.9.4 because AUR can be updated as often as the maintainer is willing to update!

We hope you will continue to work with us so that the latest FMF EMR version is always available on AUR. :-)

I'm closing this issue but the discussion can go on on freemedforms-dev mailing list or on the french Arch Linux forum "AUR Freemedforms-project" topic https://forums.archlinux.fr/viewtopic.php?f=13&t=16173

Thanks!

**Comment by EricMaeker** [comment]
Le 19/03/2015 01:25, ed0c a écrit :
> The compilation error is gone.
> Thanks again for your responsiveness !
> But do you think there is a way to make it work with the stable branch ?

Good job. Instead of adding <QVariant> header, another workthrought
could have been:

QT_BEGIN_NAMESPACE
class QVariant;
QT_END_NAMESPACE

This way compilation **could** be faster.

Thanks for the report add fix.
Eric
